### ISSUE TITLE
Model, Controller, View 

### ISSUE THREAD

**Issue by kyleMeyers** [YCPCS-481-TeamB/BaseballSim-Android#12]
Need to split the activities up into these for testing. Unsure if I can test otherwise

**Comment by bcoov** [comment]
If I'm reading [this](http://stackoverflow.com/questions/2925054/mvc-pattern-in-android) correctly, Android already structures its projects in a style of MVC, and the Activities should be the "Controllers" already.

**Comment by kyleMeyers** [comment]
You are right I think. It is just that it is hard to test our activities since they are not returning anything really just displaying it on the screen.  The function cannot be called without calling the rest so it is very hard to mock
