### ISSUE TITLE
Creating/Getting Games Played

### ISSUE THREAD

**Issue by kyleMeyers** [YCPCS-481-TeamB/BaseballSim-Android#22]
Need to get the games played for the user or create them between two teams and display the results and the game events with a UI

**Comment by bcoov** [comment]
To get history of games played:
- Perform authorized GET to /api/games

To create game:
- Perform authorized POST to /api/games
- Requires team1_id & team2_id in POST body

To start game:
- approval/user/pending : shows current user's pending approvals
- approval/:itemid/status : POST to set status for approval (where :itemid = approval item)
  - Status options: approved, declined, pending
- Approve game (both teams, see above)
- Perform POST to /api/games/:id/start (either team, but both must have approved)

To get next game event:
- POST to /api/games/:id/events/next (returns stats on that event)
- GET to /api/games/:id/events/ for all game events (:id = gameid)

**Comment by kyleMeyers** [comment]
We can get the games played and created now. Just need a UI to show them
