### ISSUE TITLE
Authentication with the Backend

### ISSUE THREAD

**Issue by kyleMeyers** [YCPCS-481-TeamB/BaseballSim-Android#5]
Json queries now work but we need authentication for the players, fields etc

**Comment by bcoov** [comment]
Update on progress: Authentication is _almost_ working. Still trying to get the authentication params to POST properly in Java.

**Comment by kyleMeyers** [comment]
Need to show info from the database with Android now

**Comment by bcoov** [comment]
Showing information (at a basic level) is now working. As far as authentication is concerned though, that part is done.
