### ISSUE TITLE
Option to create a new user

### ISSUE THREAD

**Issue by bcoov** [YCPCS-481-TeamB/BaseballSim-Android#8]
Add an option to the LoginActivity to create a new user via the Android interface. Should be doable with an additional button that performs the user creation and then the normal authentication procedure.

**Comment by bcoov** [comment]
Process:
- Endpoint: baseballsim.herokuapp.com/api/users
- Requires POST
- Data in body: username, password; Optional - firstname, lastname, email

**Comment by kyleMeyers** [comment]
Ben successfully created the option for a new user
