### ISSUE TITLE
Obtaining and displaying backend DB information

### ISSUE THREAD

**Issue by bcoov** [YCPCS-481-TeamB/BaseballSim-Android#9]
Obtain information from the backend to then display to the interface via the appropriate activity.

Current state:
- Information is obtainable (via working authentication)
- Returned as JSON
- Basic parsing and displaying is done withing MainActivity
  - Thought: should MainActivity be renamed to PlayersActivity?

Goal from this point is to expand this process to teams/leagues/games/etc, and eventually make the displaying of info more robust.

**Comment by kyleMeyers** [comment]
We can display backend info now. Can be reopened if need be but I do not think so
